name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/sensorsimulators .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sensorsimulators:latest

  deploy:
    needs: build
    runs-on: [windows-latest]
    steps:
      - name: Check and Install Docker
        run: |
          if (Get-Command docker -ErrorAction SilentlyContinue) {
            Write-Host "Docker is already installed"
          } else {
            Write-Host "Docker not found. Installing Docker Desktop..."
            # Download Docker Desktop installer
            Invoke-WebRequest -Uri "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe" -OutFile "DockerDesktopInstaller.exe"
            # Install Docker Desktop
            Start-Process -FilePath ".\DockerDesktopInstaller.exe" -ArgumentList "install", "--quiet" -Wait
            Write-Host "Docker Desktop installed. Please restart the runner."
          }
        shell: powershell
      - name: Verify Docker installation
        run: |
          docker --version
          docker info
        shell: powershell
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/sensorsimulators:latest
        shell: powershell
      - name: Delete old container
        run: |
          $containerExists = docker ps -a --format "table {{.Names}}" | Select-String -Pattern "nodejs-app-container"
          if ($containerExists) {
            Write-Host "Stopping and removing existing container..."
            docker stop nodejs-app-container
            docker rm nodejs-app-container
          } else {
            Write-Host "No existing container found"
          }
        shell: powershell
      - name: Run docker container
        run: |
          Write-Host "Starting new container..."
          docker run -d -p 5000:5000 --name nodejs-app-container ${{ secrets.DOCKER_USERNAME }}/sensorsimulators:latest
          Write-Host "Container started successfully"
          docker ps
        shell: powershell
